version: "2"
services:
  nginx:
    image: nginx-one-moesif-docker-demo
    build: .
    ports:
      - "8000:80"
    restart: always
    environment:
      - NGINX_LICENSE_JWT=
      - NGINX_AGENT_SERVER_TOKEN=
      - NGINX_AGENT_SERVER_GRPCPORT=443
      - NGINX_AGENT_SERVER_HOST=agent.connect.nginx.com
      - NGINX_AGENT_TLS_ENABLE=true
